[package]
name = "srt-move"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srtlib = { git = "https://github.com/Bukkk/srtlib.git", branch = "master" }
